# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.utils.helpers as module_0
import py_backwards.exceptions as module_1
import re as module_2


def test_case_0():
    list_0 = []
    none_type_0 = module_0.debug(list_0)


def test_case_1():
    variables_generator_0 = module_0.VariablesGenerator()


def test_case_2():
    none_type_0 = None
    callable_0 = module_0.eager(none_type_0)
    callable_0.__repr__(none_type_0)


def test_case_3():
    float_0 = 1081.53
    module_0.get_source(float_0)


def test_case_4():
    str_0 = "U~]aWk)\x0c"
    none_type_0 = module_0.warn(str_0)


def test_case_5():
    bool_0 = False
    transformation_error_0 = module_1.TransformationError(
        bool_0, bool_0, bool_0, bool_0
    )
    str_0 = "..}7/\t"
    none_type_0 = module_0.debug(bool_0)
    variables_generator_0 = module_0.VariablesGenerator()
    none_type_1 = module_0.warn(str_0)
    none_type_2 = module_0.debug(transformation_error_0)
    callable_0 = module_0.eager(none_type_2)
    module_2.sub(str_0, callable_0, str_0)
