# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import re as module_0
import py_backwards.utils.helpers as module_1
import py_backwards.exceptions as module_2


def test_case_0():
    var_0 = module_0.purge()
    none_type_0 = module_1.debug(var_0)


def test_case_1():
    variables_generator_0 = module_1.VariablesGenerator()


def test_case_2():
    var_0 = module_0.purge()
    callable_0 = module_1.eager(var_0)


def test_case_3():
    bytes_0 = b"\xd7z\xdd\x7f\x008"
    none_type_0 = module_1.debug(bytes_0)
    module_1.get_source(none_type_0)


def test_case_4():
    str_0 = "HKB~0kqXyM4s~uJ/-);q"
    none_type_0 = module_1.warn(str_0)


def test_case_5():
    bytes_0 = b"\xa7\xd9Z\xccR"
    var_0 = module_1.eager(bytes_0)
    var_1 = module_2.CompilationError(var_0, var_0, var_0, var_0)
    var_0.__call__(bytes_0, var_0)
