# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.utils.helpers as module_0
import py_backwards.exceptions as module_1


def test_case_0():
    float_0 = 2988.03
    none_type_0 = module_0.debug(float_0)


def test_case_1():
    variables_generator_0 = module_0.VariablesGenerator()


def test_case_2():
    str_0 = "YW{-Z\\ ;"
    none_type_0 = module_0.warn(str_0)
    callable_0 = module_0.eager(str_0)
    callable_1 = module_0.eager(callable_0)
    callable_2 = module_0.eager(str_0)
    str_1 = "!<7T@eS5!C?kz"
    none_type_1 = None
    compilation_error_0 = module_1.CompilationError(
        str_1, str_1, none_type_1, none_type_1
    )
    none_type_2 = module_0.debug(compilation_error_0)


def test_case_3():
    none_type_0 = None
    callable_0 = module_0.eager(none_type_0)
    callable_1 = module_0.eager(callable_0)
    none_type_1 = None
    module_0.get_source(none_type_1)


def test_case_4():
    complex_0 = -896.2605 - 3988.883j
    none_type_0 = module_0.warn(complex_0)
    float_0 = 2988.03
    none_type_1 = module_0.debug(float_0)


def test_case_5():
    str_0 = 'q\nsS7,"[n'
    callable_0 = module_0.eager(str_0)
    callable_0.__call__(callable_0, callable_0, start=callable_0)
